export type {
  AgentMarkupConfig,
  JsonLdBase,
  SchemaConfig,
  SchemaPreset,
  CustomSchema,
  WebSiteSchema,
  OrganizationSchema,
  ArticleSchema,
  FaqPageSchema,
  ProductSchema,
  OfferSchema,
  OfferData,
  LlmsTxtConfig,
  LlmsTxtSection,
  LlmsTxtEntry,
  AiCrawlersConfig,
  CrawlerDirective,
  PageConfig,
  ValidationResult,
  ValidationSeverity,
} from '@agentmarkup/core';
